### ISSUE TITLE
CI: Better Build and Test process - selective build and test

### ISSUE THREAD

**Issue by howardyoo** [astronomer/ap-vendor#394]
# Problem
Currently, if there is a change in the repo, the 'whole' build process starts - which means it tries to re-build and test everything that is in the ap-vendor repo.
- Time consuming
- Involves unnecessary test/validation of other images
- Hinders overall CI experience

# Solution
Check and retrieve only the images that have changed, and only perform build/tests on those images, by changing the way current circle ci is configured.

**Comment by pgvishnuram** [comment]
generally any updates to image - we only approve those images and merge them to master and release

**Comment by danielhoherd** [comment]
Closing as a duplicate of https://github.com/astronomer/issues/issues/1795

**Comment by danielhoherd** [comment]
@howardyoo if you want you can look at the new ap-vendor process that was merged in https://github.com/astronomer/ap-vendor/pull/478 and see if you still find areas for improvement.

**Comment by howardyoo** [comment]
Hi @danielhoherd , I believe I am satisfied with the improvements included in #478 , so I will rest in peace :-). Thank you for letting me know!
